### PR TITLE
[WIP] PlatformConfig: Enable more FULL_TREBLE properties

### PR DESCRIPTION
**Pull request by ix5**
### Enable more FULL_TREBLE properties

Tama should be capable of fulfilling almost all treble requirements

- Make implicit usage of VNDK explicit
- Enforce vintf manifest, should help catch more fcm errors early
- Move and split sepolicy from root to (/system|/vendor)/etc/selinux
- Enforce use of linker namespaces

### CODE REVIEW

**Comment by jerpelea** [comment]
why did you close them?

**Comment by ix5** [comment]
- Sepolicy change is not compatible with our `not_full_treble()` macros
- VNDK is already set
- VNDK activates linker namespaces already
- Marijn and me are gonna fix our DM and DCM and then PR it in common

So this PR is obsolete, across all platforms.

**Comment by jerpelea** [comment]
k

**Comment by ix5** [comment]
In case anyone wants to know more, this article should help understand the motivation for this: https://sx.ix5.org/info/treble-properties/
As well as the guides on source.android.com

**Pull request closed without merging**
