### PR TITLE
[TAMA] ACDB/Audio fixes and enhancements 

### PR DESCRIPTION
**Pull request by kholk**

### CODE REVIEW

**Comment by richardtullberg** [comment]
In https://github.com/sonyxperiadev/device-sony-tama/commit/3535f06d4e64d7c10ef350392ee9dbf3fe77b56c#diff-b30378d9a4cc583e1c37c7f983bd42d9
I cleaned up everything not being used, I might have done something wrong here but what I noticed is that
        <device name="SND_DEVICE_IN_HEADSET_MIC_FLUENCE" acdb_id="579"/>
        <device name="SND_DEVICE_IN_HANDSET_STEREO_DMIC" acdb_id="544"/>
was removed and they don't seem to exist on msm8974 and that

**Comment by richardtullberg** [comment]
Yes you are correct according to what I did in Yoshino/Maple, I have just missed the differences between msm8916 and msm8974. Will need to fix that discrepency.

**Comment by richardtullberg** [comment]
You will need to rebase your work unfortunately because I stole your camera fix and added a voip fix so that the patches were "Fixed" due to my error in platform, i took patches from msm8916 and applied to msm8974 and for 2 usecases that will diff.

https://github.com/sonyxperiadev/device-sony-tama/compare/master...richardtullberg:FIXUP?expand=1

**Comment by kholk** [comment]
First of all, thanks for reviewing.

So, the SND_DEVICE_OUT_AFE_PROXY was actually a misunderstanding on my side: you're correct, there is no afe proxy in the msm8974 platform on AOSP and that's only giving issues.
It's not even necessary to port the msm8916 patches to msm8974, because actually... Google's sdm845 crosshatch works -without- that thingy and being it shipped I trust their judgement and their testing, so if they didn't think that this was necessary, then I think that the best way to handle that is to just agree with them.
I'll remove that patch.

Regarding the LOW_LATENCY id, that one comes from a couple of logs taken from stock :D

And..... the SND_DEVICE_IN_CAMCORDER_MIC thingy... well, we had usages of that one in the past and if things changed along the way.... I don't know. But anyway, this is a valid id for this device and there is a possible usecase for it, so my thought at the moment of writing it was that we anyway want it for at least completeness.
Getting to the point, though, in msm8974 platform.c, the HAL doesn't seem to care about mono or dual mic usecases when the source is AUDIO_SOURCE_CAMCORDER: it just checks if the input is BUILTIN_MIC _or_ BACK_MIC and selects the CAMCORDER_MIC, so we should be using it, anyway.

About the HANDSET_MIC_FLUENCE and HANDSET_STEREO_DMIC, I agree... and... I didn't write any entry about these in the commits here in my PR... so.... I see no problem!
Maybe you wanted to say something about VOICE_REC_DMIC_FLUENCE? If you confused the names, then yeah that one is implemented in the 8974 platform.

Anyway, I will rebase the PR: no problem!

**Comment by jerpelea** [comment]
please rebase

**Comment by kholk** [comment]
This PR has been rebased over a new branch. Closing this.

Refer to the rebased PR: https://github.com/sonyxperiadev/device-sony-tama/pull/27

**Pull request closed without merging**
